server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|webp|xml|txt)$ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public";
    }
}
